sonar.projectKey=stephenlclarke_devcontainer
sonar.organization=stephenlclarke
sonar.projectName=devcontainer
sonar.sources=Sources
sonar.tests=Tests,Tools
sonar.sourceEncoding=UTF-8
sonar.exclusions=.build/**,_site/**,dist/**
sonar.coverageReportPaths=coverage.xml
