sonar.projectKey=stephenlclarke_devcontainer
sonar.organization=stephenlclarke
sonar.projectName=devcontainer
sonar.sources=Sources
sonar.tests=Tests,Tools
sonar.sourceEncoding=UTF-8
sonar.exclusions=.build/**,_site/**,dist/**
sonar.coverage.exclusions=Sources/DevContainerCLI/DevContainerCommand.swift,Sources/DevContainerCore/DevContainerProject.swift
sonar.coverageReportPaths=coverage.xml
sonar.python.version=3.10
