# Copyright 2026 devcontainer project authors. SPDX-License-Identifier: Apache-2.0
"""Generate Swift trust identities for the two static Linux launcher ELFs."""

from __future__ import annotations

import hashlib
from pathlib import Path
import struct
import sys


EXPECTED_MACHINES = {"arm64": 183, "amd64": 62}


def inspect_elf(path: Path, architecture: str) -> str:
    data = path.read_bytes()
    if len(data) < 64 or data[:4] != b"\x7fELF" or data[4:6] != b"\x02\x01":
        raise ValueError(f"{architecture} launcher is not a little-endian ELF64 image")
    if struct.unpack_from("<H", data, 18)[0] != EXPECTED_MACHINES[architecture]:
        raise ValueError(f"{architecture} launcher has the wrong ELF machine")
    program_offset = struct.unpack_from("<Q", data, 32)[0]
    entry_size, count = struct.unpack_from("<HH", data, 54)
    if entry_size < 56 or program_offset + entry_size * count > len(data):
        raise ValueError(f"{architecture} launcher has an invalid ELF program table")
    for index in range(count):
        entry = program_offset + index * entry_size
        if struct.unpack_from("<I", data, entry)[0] == 3:
            raise ValueError(f"{architecture} launcher is dynamically linked")
    return hashlib.sha256(data).hexdigest()


def swift_source(arm64: Path, amd64: Path) -> str:
    hashes = {"arm64": inspect_elf(arm64, "arm64"), "amd64": inspect_elf(amd64, "amd64")}
    return (
        "// Copyright 2026 devcontainer project authors. SPDX-License-Identifier: Apache-2.0\n"
        "// Generated by Tools/bazel/terminal_launcher_identity.py.\n"
        "internal enum NativeTerminalLauncherIdentity {\n"
        "    static let sha256ByArchitecture: [String: String] = [\n"
        f'        "arm64": "{hashes["arm64"]}",\n'
        f'        "amd64": "{hashes["amd64"]}",\n'
        "    ]\n"
        "}\n"
    )


def main(argv: list[str]) -> None:
    if len(argv) != 4:
        raise SystemExit("usage: terminal_launcher_identity.py OUTPUT ARM64_ELF AMD64_ELF")
    output, arm64, amd64 = map(Path, argv[1:])
    output.write_text(swift_source(arm64, amd64), encoding="utf-8")


if __name__ == "__main__":
    main(sys.argv)
